### ISSUE TITLE
error

### ISSUE THREAD

**Issue by justnjbo** [Kisakay/OperaGX-DiscordNitro-Gen#1]
Error: Os { code: 2, kind: NotFound, message: "Impossibile trovare il file specificato." }
error: process didn't exit successfully: `target\debug\proxy_txt_parser.exe` (exit code: 1)

**Comment by Kisakay** [comment]
Ensure you verified the path of the `input.txt`
In your case, you want to parse the proxy, right ?

if you run the program with the .exe located in the `target/debug/` folder, please moove-him to the project directory.

Or just run the program with `cargo run`

Note: For a better response quality, don’t forget to send a good context when you make an issue.

**Comment by Kisakay** [comment]
Closed for inactivity
